In [ ]:
# Day2 Introduction to python_libraries_numpy_and_pandas

In [ ]:
# NUMPY - for calculations

In [2]:
import numpy
import numpy as np

In [3]:
# creating a 1 demsional array

x = np.array([1,2,3,4,5])
y = np.array([9,10])
print(x)
print('The shape of x is', x.shape)

print(y)
print('The shape of y is', y.shape)


[1 2 3 4 5]
The shape of x is (5,)
[ 9 10]
The shape of y is (2,)


In [4]:
# creating 2D arrays
z = np.array([[1,2], [3,4]])

print(z)
print('The shape of z is', z.shape)

[[1 2]
 [3 4]]
The shape of z is (2, 2)


In [6]:
# creating a multidimensuinal array

w = np.array([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]], [[19,20,21], [22,23,24], [25,26,27]]])
print(w, '\n')
print('The shape of w is', w.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 

The shape of w is (3, 3, 3)


In [12]:
# arrange is used to create arrays with values in a specified way
 
A10 = np.arange(10)
A10
print(A10)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
A10 = np.arange(10)
A10
print(A10.shape)

(10,)


In [14]:
# to change a scalar matrix to vector
#vector matrix = with one column

B10 = A10.reshape(-1,1)

print( A10, '\n', B10)
print('The shape of 1D array X = ', B10.shape)

[0 1 2 3 4 5 6 7 8 9] 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
The shape of 1D array X =  (10, 1)


In [15]:
A10 = B10.reshape(2,5)

print ( A10)
print ('The shape if 1D array X = ', A10.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
The shape if 1D array X =  (2, 5)


In [16]:
#zeros is used to create an array filled with zeros

np_Zeros = np.zeros((2,3))
np_Zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:

np_Zeros = np.zeros((2,3))
np_Zeros.astype(int)

array([[0, 0, 0],
       [0, 0, 0]])

In [17]:
np_zeros = np.zeros((5,6))
np_zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
#ones is used to create an array filled with ones
np_Ones = np.ones((2,3))
np_Ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
#functions creates a n* n array filled with a specified given value
np_full = np.full((2,3), 4)

np_full

array([[4, 4, 4],
       [4, 4, 4]])

In [25]:
np_eye = np.eye(6,6)

np_eye

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [27]:
#linspace returns evenly spaced numbers over a specified value
np_linspace = np.linspace(0, 10, num = 6)

np.linspace

<function numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)>

In [28]:
#linspace returns evenly spaced numbers over a specified value
np_linspace = np.linspace(0, 10, num = 5)

np.linspace

<function numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)>

In [29]:
#this creates an array filled with random vlaues between o and 1
np_rand = np.random.random_sample((2,3))

np_rand1 = np.random.rand(2,3)

x = np.random.randint(10, size=(5,3))

print(np_rand)

print(np_rand1)
x

[[0.91572519 0.81113106 0.40391791]
 [0.48544967 0.96952325 0.73830214]]
[[0.08754105 0.97880627 0.17303142]
 [0.26228315 0.21598557 0.13155273]]


array([[8, 3, 0],
       [0, 1, 2],
       [6, 3, 9],
       [7, 7, 3],
       [6, 3, 3]])

In [31]:
#this creates an array filled with random vlaues between o and 1
np_rand = np.random.random_sample((2,3))

np_rand1 = np.random.rand(2,3)

x = np.random.randint(10, size=(5,3))
np.save('array_data.npy', np_rand)

print(np_rand)

print(np_rand1)
print(x)
print(np_rand)

[[0.27022953 0.76982073 0.85485776]
 [0.7131088  0.85083551 0.17730267]]
[[0.56813448 0.48595592 0.63163525]
 [0.18970474 0.71255918 0.81718444]]
[[9 5 8]
 [2 0 2]
 [7 2 7]
 [5 1 9]
 [7 6 1]]
[[0.27022953 0.76982073 0.85485776]
 [0.7131088  0.85083551 0.17730267]]


In [32]:
#row 1, column 0 gives a scalar
print(z)
z[1,0]

[[1 2]
 [3 4]]


3

In [34]:
#row 1, column 0 gives a scalar
print(z)
z[1,0]
[[1, 2], [3, 4]]

[[1 2]
 [3 4]]


[[1, 2], [3, 4]]

In [37]:
#row 1, column 0 gives a scalar
print(z)
z[1,1]

[[1 2]
 [3 4]]


4

In [38]:
#or

p = z[1][0]

p

3

In [40]:
p = np.array([[1,2], [3,4]])
print(p)

[[1 2]
 [3 4]]


In [39]:
p = z[1][0]

p

3

In [41]:
p = (z[0:1, 0])
p

array([1])

# numpy attributes

In [45]:
print ('The Dtype of element in array X= ', x.dtype)

print ('The shape of ND array w=', w.dytpe)

The Dtype of element in array X=  int32


AttributeError: 'numpy.ndarray' object has no attribute 'dytpe'

In [46]:
print ('The shape of 1D array X = ', x.shape)
print ('The shape of 2D array Z = ', z.shape)
print ('The shape of ND array W = ', w.shape)
print ('The shape of arange A10 = ', A10.shape)

The shape of 1D array X =  (5, 3)
The shape of 2D array Z =  (2, 2)
The shape of ND array W =  (3, 3, 3)
The shape of arange A10 =  (2, 5)


In [47]:
print ('The shape of ND array W = ', w.size)
print ('The shape of arange A10 = ', A10.size)

The shape of ND array W =  27
The shape of arange A10 =  10


In [48]:
x = np.array([[1,2,3],[4,5,6]])
x = np.array([[2,2,2],[3,3,3]])
x = np.array([1,2,3])

In [49]:
#transpose a matrix

x.T

array([[1, 4],
       [2, 5],
       [3, 6]])